export const GET_SEARCH_RESULT_SUCCESS = "GET_SEARCH_RESULT_SUCCESS";
export const GET_SEARCH_RESULT_REQUEST = "GET_SEARCH_RESULT_REQUEST";
export const GET_SEARCH_RESULT_FAILURE = "GET_SEARCH_RESULT_FAILURE";

export const GET_COMPARISON_LIST_REQUEST = "GET_COMPARISON_LIST_REQUEST";
export const GET_COMPARISON_LIST_SUCCESS = "GET_COMPARISON_LIST_SUCCESS";
export const GET_COMPARISON_LIST_FAILURE = "GET_COMPARISON_LIST_FAILURE";