export const GET_MATCHES_LIST_REQUEST = "GET_MATCHES_LIST_REQUEST";
export const GET_MATCHES_LIST_SUCCESS = "GET_MATCHES_LIST_SUCCESS";
export const GET_MATCHES_LIST_FAILURE = "GET_MATCHES_LIST_FAILURE";



